In [11]:
import pandas as pd
import seaborn as sns
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt

In [12]:
diamonds = sns.load_dataset('diamonds')

In [13]:
X

       carat color clarity  depth  table  price     x     y     z
0       0.23     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 9 columns]

In [14]:
y

0            Ideal
1          Premium
2             Good
3          Premium
4             Good
           ...
53935        Ideal
53936         Good
53937    Very Good
53938      Premium
53939        Ideal
Name: cut, Length: 53940, dtype: category
Categories (5, object): ['Ideal', 'Premium', 'Very Good', 'Good', 'Fair']

In [16]:
X = diamonds.drop("cut",axis = 1)
y = diamonds["cut"]

In [17]:
X

       carat color clarity  depth  table  price     x     y     z
0       0.23     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 9 columns]

In [34]:
X.dtypes

carat       float64
color      category
clarity    category
depth       float64
table       float64
price         int64
x           float64
y           float64
z           float64
dtype: object

In [18]:
y

0            Ideal
1          Premium
2             Good
3          Premium
4             Good
           ...
53935        Ideal
53936         Good
53937    Very Good
53938      Premium
53939        Ideal
Name: cut, Length: 53940, dtype: category
Categories (5, object): ['Ideal', 'Premium', 'Very Good', 'Good', 'Fair']

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [38]:
categorial_features = X.select_dtypes(include = ["category"]).columns.tolist()
numerical_features = X.select_dtypes(include=['float64','int64']).columns.tolist()

In [39]:
X.select_dtypes(include = ["category"])

      color clarity
0         E     SI2
1         E     SI1
2         E     VS1
3         I     VS2
4         J     SI2
...     ...     ...
53935     D     SI1
53936     D     SI1
53937     D     SI1
53938     H     SI2
53939     D     SI2

[53940 rows x 2 columns]

In [40]:
X.select_dtypes(include=['float64','int64'])

       carat  depth  table  price     x     y     z
0       0.23   61.5   55.0    326  3.95  3.98  2.43
1       0.21   59.8   61.0    326  3.89  3.84  2.31
2       0.23   56.9   65.0    327  4.05  4.07  2.31
3       0.29   62.4   58.0    334  4.20  4.23  2.63
4       0.31   63.3   58.0    335  4.34  4.35  2.75
...      ...    ...    ...    ...   ...   ...   ...
53935   0.72   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 7 columns]

In [42]:
preprocessor = ColumnTransformer(
   transformers=[
       ("cat", OneHotEncoder(), categorial_features),
       ("num", StandardScaler(), numerical_features),
   ]
)

In [43]:
pipeline = Pipeline(
    [
        ("preprocessor", preprocessor),
        ("classifier",GradientBoostingClassifier(random_state=42))
    ]
)

In [44]:
# Perform 5-fold cross-validation
cv_scores = cross_val_score(pipeline, X_train, y_train, cv=5)

# Fit the model on the training data
pipeline.fit(X_train, y_train)

# Predict on the test set
y_pred = pipeline.predict(X_test)

# Generate classification report
report = classification_report(y_test, y_pred)