In [1]:
import torch
import torch.nn as nn
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('data.csv')

In [3]:
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [4]:
df.describe()

,id,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
count,5.690000e+02,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,...,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,0.0
mean,3.037183e+07,14.127292,19.289649,91.969033,654.889104,0.096360,0.104341,0.088799,0.048919,0.181162,...,25.677223,107.261213,880.583128,0.132369,0.254265,0.272188,0.114606,0.290076,0.083946,NaN
std,1.250206e+08,3.524049,4.301036,24.298981,351.914129,0.014064,0.052813,0.079720,0.038803,0.027414,...,6.146258,33.602542,569.356993,0.022832,0.157336,0.208624,0.065732,0.061867,0.018061,NaN
min,8.670000e+03,6.981000,9.710000,43.790000,143.500000,0.052630,0.019380,0.000000,0.000000,0.106000,...,12.020000,50.410000,185.200000,0.071170,0.027290,0.000000,0.000000,0.156500,0.055040,NaN
25%,8.692180e+05,11.700000,16.170000,75.170000,420.300000,0.086370,0.064920,0.029560,0.020310,0.161900,...,21.080000,84.110000,515.300000,0.116600,0.147200,0.114500,0.064930,0.250400,0.071460,NaN
50%,9.060240e+05,13.370000,18.840000,86.240000,551.100000,0.095870,0.092630,0.061540,0.033500,0.179200,...,25.410000,97.660000,686.500000,0.131300,0.211900,0.226700,0.099930,0.282200,0.080040,NaN
75%,8.813129e+06,15.780000,21.800000,104.100000,782.700000,0.105300,0.130400,0.130700,0.074000,0.195700,...,29.720000,125.400000,1084.000000,0.146000,0.339100,0.382900,0.161400,0.317900,0.092080,NaN
max,9.113205e+08,28.110000,39.280000,188.500000,2501.000000,0.163400,0.345400,0.426800,0.201200,0.304000,...,49.540000,251.200000,4254.000000,0.222600,1.058000,1.252000,0.291000,0.663800,0.207500,NaN

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       569 non-null    int64
 1   diagnosis                569 non-null    object
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             569 non-null    float64
 15  area_se                  569 non-null    float64
 16  smoothness_se            569 non-null    float64
 17  compactness_se           569 non-null    float64
 18  concavity_se             569 non-null    float64
 19  concave points_se        569 non-null    float64
 20  symmetry_se              569 non-null    float64
 21  fractal_dimension_se     569 non-null    float64
 22  radius_worst             569 non-null    float64
 23  texture_worst            569 non-null    float64
 24  perimeter_worst          569 non-null    float64
 25  area_worst               569 non-null    float64
 26  smoothness_worst         569 non-null    float64
 27  compactness_worst        569 non-null    float64
 28  concavity_worst          569 non-null    float64
 29  concave points_worst     569 non-null    float64
 30  symmetry_worst           569 non-null    float64
 31  fractal_dimension_worst  569 non-null    float64
 32  Unnamed: 32              0 non-null      float64
dtypes: float64(31), int64(1), object(1)
memory usage: 146.8+ KB

In [6]:
df.drop(['id', 'Unnamed: 32'], axis=1, inplace=True)

In [7]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [8]:
X_train,X_test, y_train,y_test= train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size = 0.2, random_state = 42)

In [9]:
X_train.shape

(455, 30)

In [10]:
y_train.shape

(455,)

In [11]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
y_train = LabelEncoder().fit_transform(y_train)
y_test = LabelEncoder().fit_transform(y_test)

In [12]:
X_train_tensor = torch.tensor(X_train).cpu()
X_test_tensor = torch.tensor(X_test).cpu()
y_train_tensor = torch.tensor(y_train).cpu()
y_test_tensor = torch.tensor(y_test).cpu()

In [13]:
X_train_tensor

tensor([[-1.4408, -0.4353, -1.3621,  ...,  0.9320,  2.0972,  1.8865],
        [ 1.9741,  1.7330,  2.0917,  ...,  2.6989,  1.8912,  2.4978],
        [-1.4000, -1.2496, -1.3452,  ..., -0.9702,  0.5976,  0.0579],
        ...,
        [ 0.0488, -0.5550, -0.0651,  ..., -1.2390, -0.7086, -1.2715],
        [-0.0390,  0.1021, -0.0314,  ...,  1.0500,  0.4343,  1.2134],
        [-0.5486,  0.3133, -0.6035,  ..., -0.6110, -0.3345, -0.8463]],
       dtype=torch.float64)

In [14]:
class MySimpleNN():
    def __init__(self,X):
        self.weights = torch.rand(X_train_tensor.shape[1],1, requires_grad=True, dtype=torch.float64)
        self.bias = torch.rand(1,requires_grad=True,dtype= torch.float64)
    def forward(self,X):
        z = torch.matmul(X,self.weights)+self.bias
        y_pred = torch.sigmoid(z)
        return y_pred
    def loss_function(self, y_pred, y):
        
        
    # Clamp predictions to avoid log(0)
        epsilon = 1e-7
        
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)
        

    # Calculate loss
        loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
        return loss

In [15]:
learning_rate = 0.1
epochs = 30
model = MySimpleNN(X_train_tensor)
for epoch in range(epochs):
    #forward pass
    y_pred = model.forward(X_train_tensor)
    #loss calculation
    loss = model.loss_function(y_pred, y_train_tensor)
    #backward pass
    loss.backward()
    #update weights 
    with torch.no_grad():
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad
        model.weights.grad.zero_()
        model.bias.grad.zero_()
    #print loss
    print(f'Epoch {epoch+1}/{epochs}, Loss: {loss.item():.4f}')

Epoch 1/30, Loss: 3.6813
Epoch 2/30, Loss: 3.5617
Epoch 3/30, Loss: 3.4371
Epoch 4/30, Loss: 3.3041
Epoch 5/30, Loss: 3.1710
Epoch 6/30, Loss: 3.0368
Epoch 7/30, Loss: 2.9013
Epoch 8/30, Loss: 2.7638
Epoch 9/30, Loss: 2.6181
Epoch 10/30, Loss: 2.4694
Epoch 11/30, Loss: 2.3178
Epoch 12/30, Loss: 2.1627
Epoch 13/30, Loss: 2.0101
Epoch 14/30, Loss: 1.8587
Epoch 15/30, Loss: 1.7121
Epoch 16/30, Loss: 1.5735
Epoch 17/30, Loss: 1.4433
Epoch 18/30, Loss: 1.3196
Epoch 19/30, Loss: 1.2123
Epoch 20/30, Loss: 1.1222
Epoch 21/30, Loss: 1.0487
Epoch 22/30, Loss: 0.9905
Epoch 23/30, Loss: 0.9452
Epoch 24/30, Loss: 0.9104
Epoch 25/30, Loss: 0.8836
Epoch 26/30, Loss: 0.8626
Epoch 27/30, Loss: 0.8459
Epoch 28/30, Loss: 0.8323
Epoch 29/30, Loss: 0.8208
Epoch 30/30, Loss: 0.8109

In [16]:
print(model)

<__main__.MySimpleNN object at 0x0000019A420EA510>

In [17]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.97).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.6206524968147278

#  NN Module

In [18]:
import pandas as pd
import numpy as np
import torch
import torch.nn as nn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder

In [19]:
df1 = pd.read_csv('data.csv')
df1.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [20]:
df1.shape

(569, 33)

In [21]:
df1.drop(columns = ['id', 'Unnamed: 32'],inplace=True)

In [22]:
df1.describe()

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
count,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,...,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000
mean,14.127292,19.289649,91.969033,654.889104,0.096360,0.104341,0.088799,0.048919,0.181162,0.062798,...,16.269190,25.677223,107.261213,880.583128,0.132369,0.254265,0.272188,0.114606,0.290076,0.083946
std,3.524049,4.301036,24.298981,351.914129,0.014064,0.052813,0.079720,0.038803,0.027414,0.007060,...,4.833242,6.146258,33.602542,569.356993,0.022832,0.157336,0.208624,0.065732,0.061867,0.018061
min,6.981000,9.710000,43.790000,143.500000,0.052630,0.019380,0.000000,0.000000,0.106000,0.049960,...,7.930000,12.020000,50.410000,185.200000,0.071170,0.027290,0.000000,0.000000,0.156500,0.055040
25%,11.700000,16.170000,75.170000,420.300000,0.086370,0.064920,0.029560,0.020310,0.161900,0.057700,...,13.010000,21.080000,84.110000,515.300000,0.116600,0.147200,0.114500,0.064930,0.250400,0.071460
50%,13.370000,18.840000,86.240000,551.100000,0.095870,0.092630,0.061540,0.033500,0.179200,0.061540,...,14.970000,25.410000,97.660000,686.500000,0.131300,0.211900,0.226700,0.099930,0.282200,0.080040
75%,15.780000,21.800000,104.100000,782.700000,0.105300,0.130400,0.130700,0.074000,0.195700,0.066120,...,18.790000,29.720000,125.400000,1084.000000,0.146000,0.339100,0.382900,0.161400,0.317900,0.092080
max,28.110000,39.280000,188.500000,2501.000000,0.163400,0.345400,0.426800,0.201200,0.304000,0.097440,...,36.040000,49.540000,251.200000,4254.000000,0.222600,1.058000,1.252000,0.291000,0.663800,0.207500

In [23]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   diagnosis                569 non-null    object
 1   radius_mean              569 non-null    float64
 2   texture_mean             569 non-null    float64
 3   perimeter_mean           569 non-null    float64
 4   area_mean                569 non-null    float64
 5   smoothness_mean          569 non-null    float64
 6   compactness_mean         569 non-null    float64
 7   concavity_mean           569 non-null    float64
 8   concave points_mean      569 non-null    float64
 9   symmetry_mean            569 non-null    float64
 10  fractal_dimension_mean   569 non-null    float64
 11  radius_se                569 non-null    float64
 12  texture_se               569 non-null    float64
 13  perimeter_se             569 non-null    float64
 14  area_se                  569 non-null    float64
 15  smoothness_se            569 non-null    float64
 16  compactness_se           569 non-null    float64
 17  concavity_se             569 non-null    float64
 18  concave points_se        569 non-null    float64
 19  symmetry_se              569 non-null    float64
 20  fractal_dimension_se     569 non-null    float64
 21  radius_worst             569 non-null    float64
 22  texture_worst            569 non-null    float64
 23  perimeter_worst          569 non-null    float64
 24  area_worst               569 non-null    float64
 25  smoothness_worst         569 non-null    float64
 26  compactness_worst        569 non-null    float64
 27  concavity_worst          569 non-null    float64
 28  concave points_worst     569 non-null    float64
 29  symmetry_worst           569 non-null    float64
 30  fractal_dimension_worst  569 non-null    float64
dtypes: float64(30), object(1)
memory usage: 137.9+ KB

In [24]:
df1.shape

(569, 31)

In [25]:
X_train,X_test, y_train,y_test= train_test_split(df1.iloc[:,1:],df1.iloc[:,0],test_size = 0.2, random_state = 42)

In [26]:
X_train_tensor = torch.tensor(X_train.values, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test.values, dtype=torch.float32)

In [27]:
print(X_train_tensor.device)
print(X_test_tensor.device)

cpu
cpu

In [28]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [29]:
class MySimpleNN(nn.Module):
    def __init__(self,Input_features):
        super().__init__()
        self.networks = nn.Sequential(
            nn.Linear(Input_features, 16),
            nn.ReLU(),
            nn.Linear(16, 8),
            nn.ReLU(),
            nn.Linear(8, 1),
            nn.Sigmoid()
        )
    def forward(self,features):
        out = self.networks(features)
        return out

In [30]:
model = MySimpleNN(X_train.shape[1])
import torchinfo
from torchinfo import summary
summary(model,Input_size=(25,16))

=================================================================
Layer (type:depth-idx)                   Param #
=================================================================
MySimpleNN                               --
├─Sequential: 1-1                        --
│    └─Linear: 2-1                       496
│    └─ReLU: 2-2                         --
│    └─Linear: 2-3                       136
│    └─ReLU: 2-4                         --
│    └─Linear: 2-5                       9
│    └─Sigmoid: 2-6                      --
=================================================================
Total params: 641
Trainable params: 641
Non-trainable params: 0
=================================================================

In [31]:
!pip install wandb

Requirement already satisfied: wandb in c:\users\lenovo\anaconda3\envs\test\lib\site-packages (0.23.1)
Requirement already satisfied: click>=8.0.1 in c:\users\lenovo\anaconda3\envs\test\lib\site-packages (from wandb) (8.2.1)
Requirement already satisfied: gitpython!=3.1.29,>=1.0.0 in c:\users\lenovo\anaconda3\envs\test\lib\site-packages (from wandb) (3.1.44)
Requirement already satisfied: packaging in c:\users\lenovo\anaconda3\envs\test\lib\site-packages (from wandb) (24.2)
Requirement already satisfied: platformdirs in c:\users\lenovo\anaconda3\envs\test\lib\site-packages (from wandb) (4.3.7)
Requirement already satisfied: protobuf!=4.21.0,!=5.28.0,<7,>=3.19.0 in c:\users\lenovo\anaconda3\envs\test\lib\site-packages (from wandb) (5.29.5)
Requirement already satisfied: pydantic<3 in c:\users\lenovo\anaconda3\envs\test\lib\site-packages (from wandb) (2.11.5)
Requirement already satisfied: pyyaml in c:\users\lenovo\anaconda3\envs\test\lib\site-packages (from wandb) (6.0.2)
Requirement already satisfied: requests<3,>=2.0.0 in c:\users\lenovo\anaconda3\envs\test\lib\site-packages (from wandb) (2.32.3)
Requirement already satisfied: sentry-sdk>=2.0.0 in c:\users\lenovo\anaconda3\envs\test\lib\site-packages (from wandb) (2.48.0)
Requirement already satisfied: typing-extensions<5,>=4.8 in c:\users\lenovo\anaconda3\envs\test\lib\site-packages (from wandb) (4.13.2)
Requirement already satisfied: colorama in c:\users\lenovo\anaconda3\envs\test\lib\site-packages (from click>=8.0.1->wandb) (0.4.6)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\lenovo\anaconda3\envs\test\lib\site-packages (from gitpython!=3.1.29,>=1.0.0->wandb) (4.0.12)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\lenovo\anaconda3\envs\test\lib\site-packages (from pydantic<3->wandb) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in c:\users\lenovo\anaconda3\envs\test\lib\site-packages (from pydantic<3->wandb) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in c:\users\lenovo\anaconda3\envs\test\lib\site-packages (from pydantic<3->wandb) (0.4.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\lenovo\anaconda3\envs\test\lib\site-packages (from requests<3,>=2.0.0->wandb) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\lenovo\anaconda3\envs\test\lib\site-packages (from requests<3,>=2.0.0->wandb) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\lenovo\anaconda3\envs\test\lib\site-packages (from requests<3,>=2.0.0->wandb) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\lenovo\anaconda3\envs\test\lib\site-packages (from requests<3,>=2.0.0->wandb) (2025.4.26)
Requirement already satisfied: smmap<6,>=3.0.1 in c:\users\lenovo\anaconda3\envs\test\lib\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.29,>=1.0.0->wandb) (5.0.2)

In [32]:
# Training Loop
learning_rate = 0.01
epochs = 20

# Prepare y_train_tensor with correct shape
X_train_scaled_tensor = torch.tensor(X_train_scaled, dtype=torch.float32)
y_train_encoded = LabelEncoder().fit_transform(y_train)
y_train_tensor = torch.tensor(y_train_encoded, dtype=torch.float32).unsqueeze(1)

criterion = nn.BCELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

for epoch in range(epochs):
    # Forward pass
    y_pred = model(X_train_scaled_tensor)
    
    # Compute loss
    loss = criterion(y_pred, y_train_tensor)
    
    # Backward pass and optimization
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    
    print(f'Epoch [{epoch+1}/{epochs}], Loss: {loss.item():.4f}')

Epoch [1/20], Loss: 0.6794
Epoch [2/20], Loss: 0.6792
Epoch [3/20], Loss: 0.6791
Epoch [4/20], Loss: 0.6789
Epoch [5/20], Loss: 0.6787
Epoch [6/20], Loss: 0.6785
Epoch [7/20], Loss: 0.6783
Epoch [8/20], Loss: 0.6782
Epoch [9/20], Loss: 0.6780
Epoch [10/20], Loss: 0.6778
Epoch [11/20], Loss: 0.6776
Epoch [12/20], Loss: 0.6775
Epoch [13/20], Loss: 0.6773
Epoch [14/20], Loss: 0.6771
Epoch [15/20], Loss: 0.6770
Epoch [16/20], Loss: 0.6768
Epoch [17/20], Loss: 0.6766
Epoch [18/20], Loss: 0.6765
Epoch [19/20], Loss: 0.6763
Epoch [20/20], Loss: 0.6761

In [40]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.37719297409057617